name: Exploring Variables and Secrets
run-name: Exploring Variables and Secrets run
on:
  workflow_dispatch:
  #   schedule:
  #     - cron: '*/1 * * * *'
  push:

env:
  CONTAINER_RESGISTRY: docker.io
  DOCKER_USERNAME: lolawin
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: s3cUrePaSsw0rd
jobs:
  docker_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy_job_2:
    if: github.ref == 'refs/heads/main'
    needs: docker_job_1
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-job
      cancel-in-progress: false
    timeout-minutes: 2
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
