name: Matrix Configuration

run-name: Matrix Configuration Workflow

on:
  workflow_dispatch:
  push:

jobs:
  deploy-on-ubuntu:
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{matrix.os}}
        run: docker run ${{ matrix.images }}
